defaults:
  - templates: chain_of_thought
  - config: default

_target_: medical_reasoning.models.Reasoner
engine: ???
price: ??? # price per 1k tokens
tokenizer: ${tokenizer}
max_rate: 60 # rate per minute
cache_dir: ${sys.cache_dir}
