defaults:
  - template: multiple_choice

_target_: medical_reasoning.models.Reasoner
engine: ???
prompt_mode: ${prompt_mode}
price: ??? # price per 1k tokens
tokenizer: ${tokenizer}
max_tokens: 256
max_rate: 60 # rate per minute
