# output paths for hydra logs
job:
  chdir: true
run:
  dir: ${sys.work_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
#  dir: ${sys.work_dir}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}-${exp_id}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
#job:
#  env_set:
#    CUDA_VISIBLE_DEVICES: ${hydra.job.num}"
