defaults:
  - base
  - corpus: wiki
  - /index/elasticsearch@indexes.es

_target_: medical_reasoning.indexes.CompositeIndex
p: 100
passage_length: 100
passage_stride: 50

weights:
  es: 1.0
  dpr: 1.0
  
indexes:
  es:
    _partial_: true
  dpr:
    _partial: true
