defaults:
  - base
  - es_body: default

_target_: medical_reasoning.indexes.ElasticsearchIndex
column_name: text
filter_numbers: True
corpus_name: ${index.corpus.path}-${index.corpus.name}
aux_weights:
  text: 1.0
  title: 0.5
