defaults:
  - base

_target_: medical_reasoning.indexes.MultiIndex
p: 100
weights:
  dpr: 1.1
  elasticsearch: 1.0
indexes:
  dpr:
    _partial_: true
    _target_: medical_reasoning.indexes.DprIndex
  elasticsearch:
    _partial_: true
    _target_: medical_reasoning.indexes.ElasticsearchIndex
