# @package _global_

defaults:
  - _self_
  - dataset: medqa_us
  - strategy: strat__4
  - tokenizer: gpt2
  - index: dpr
  - model: ada
  - sys: local
  - hydra: default

    # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog


exp_id: ${dataset.name}-${model.engine}-${len:${model.templates}}steps-${n_docs}doc-${shots}shots-${shorten:${strategy.prompt},32}
prompt_style: full
n_docs: 0
shots: 0
n_samples: 1
temperature: 0
max_tokens: 1024

# technicals
print_config: true
disable_caching: false
