# @package _global_

defaults:
  - _self_
  - dataset: medqa_us
  - tokenizer: gpt2
  - index: elasticsearch
  - model: ada
  - sys: local
  - hydra: default

    # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog



exp_id: ${dataset.name}-${model.engine}-${model.prompt_mode}-${model.template.identity}${if:${use_documents},"-grounded",""}
prompt_mode: "chain_of_thought"
identity: "medical_expert"
use_documents: false
topk: 1
shots: 0

# technicals
print_config: true
disable_caching: false
