# @package _global_

defaults:
  - _self_
  - dataset: medqa_us
  - model: ada
  - sys: local
  - hydra: default

    # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog



exp_id: ${dataset.name}-${model.engine}-${model.prompt_mode}
rate_limit: 0.25
print_config: true
